// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXGeukxmuFWCbNEJ3Glb4Fe_D1NMBKl9Q',
    appId: '1:740520377191:android:5fd902a085a6393fa9cdc2',
    messagingSenderId: '740520377191',
    projectId: 'hajj-28cbd',
    storageBucket: 'hajj-28cbd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkik0FnB-ADGK4WK0QjUbr4bvQqu8La1A',
    appId: '1:740520377191:ios:92be751e55d97095a9cdc2',
    messagingSenderId: '740520377191',
    projectId: 'hajj-28cbd',
    storageBucket: 'hajj-28cbd.firebasestorage.app',
    iosBundleId: 'com.example.hajj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkik0FnB-ADGK4WK0QjUbr4bvQqu8La1A',
    appId: '1:740520377191:ios:92be751e55d97095a9cdc2',
    messagingSenderId: '740520377191',
    projectId: 'hajj-28cbd',
    storageBucket: 'hajj-28cbd.firebasestorage.app',
    iosBundleId: 'com.example.hajj',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD77AFNtGK1Uo4qROqrGLhzJMMABtuDtAg',
    appId: '1:740520377191:web:2eae4049d668f135a9cdc2',
    messagingSenderId: '740520377191',
    projectId: 'hajj-28cbd',
    authDomain: 'hajj-28cbd.firebaseapp.com',
    storageBucket: 'hajj-28cbd.firebasestorage.app',
    measurementId: 'G-4T6DK3D1D0',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD77AFNtGK1Uo4qROqrGLhzJMMABtuDtAg',
    appId: '1:740520377191:web:112abfaf6f78449ca9cdc2',
    messagingSenderId: '740520377191',
    projectId: 'hajj-28cbd',
    authDomain: 'hajj-28cbd.firebaseapp.com',
    storageBucket: 'hajj-28cbd.firebasestorage.app',
    measurementId: 'G-LNRDJTZ4QP',
  );

}